### ISSUE TITLE
Bug - about the permission of lock screen

### ISSUE THREAD

**Issue by singular-steve** [lab-act/AngelTalk#8]
App crashed with the logs as follows :

APP_VERSION_NAME=2.3
CUSTOM_DATA=
PHONE_MODEL=SM-N935L
USER_COMMENT=
ANDROID_VERSION=8.0.0
BRAND=samsung
STACK_TRACE=android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@5d3f15f -- permission denied for window type 2010
at android.view.ViewRootImpl.setView(ViewRootImpl.java:982)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:381)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:100)
at act.angelman.presentation.custom.ChildModeManager.createAndAddCategoryMenu(ChildModeManager.java:34)
at act.angelman.presentation.custom.ChildModeManager$MyPhoneStateListener.processByPhoneStatus(ChildModeManager.java:94)
at act.angelman.presentation.custom.ChildModeManager$MyPhoneStateListener.onCallStateChanged(ChildModeManager.java:83)
at android.telephony.PhoneStateListener$1.handleMessage(PhoneStateListener.java:339)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6940)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by singular-steve** [comment]
https://stackoverflow.com/questions/32224452/android-unable-to-add-window-permission-denied-for-this-window-type
